apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  selector:
    matchLabels:
      app: p-ser-payment
  replicas: 1
  template:
    metadata:
      labels:
        app: p-ser-payment
    spec:
      volumes:
        - name: app-config
          configMap:
            name: app-config
      containers:
        - name: payment-container
          image: amanecopse/p-ser-payment
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/share"
              name: app-config